import localFont from "next/font/local";
import "./globals.css";

// components
import Header from "@/components/Header";
import PageTransisition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const americanCasual = localFont({
  src: "./fonts/AmericanCasual.otf",
  variable: "--font-american-casual",
  weight: "100 900",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${americanCasual.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <StairTransition />
        <PageTransisition>{children}</PageTransisition>
      </body>
    </html>
  );
}
